version 0.3.0; extraction, verbose option, checking, docs added
Some code clean-up and tweeks. Manifest format sightly changed.

diff --git a/bin/generate_archive b/bin/generate_archive
--- a/bin/generate_archive
+++ b/bin/generate_archive
@@ -1,14 +1,15 @@
 #!/bin/bash
 
-archive_gen_version="0.1.1"
+archive_generate_version="0.3.0"
 
 # Created by argbash-init v2.10.0
-# ARG_OPTIONAL_SINGLE([output],[o],[output file or - for stdout, (required)])
+# ARG_OPTIONAL_SINGLE([archive],[a],[use existing archive (tar); filename or - for stdin])
 # ARG_OPTIONAL_SINGLE([manifest],[m],[manifest file],[./manifest])
-# ARG_OPTIONAL_SINGLE([archive],[a],[process existing archive (tar)])
+# ARG_OPTIONAL_SINGLE([output],[o],[output file or - for stdout, (required)])
 # ARG_POSITIONAL_INF([sources],[sources to archive],[0],[.])
+# ARG_OPTIONAL_BOOLEAN([verbose],[],[write information to stderr])
 # ARG_HELP([Generate archive and manifest])
-# ARG_VERSION([echo $0 $archive_gen_version])
+# ARG_VERSION([echo $0 $archive_generate_version])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
 ### START OF CODE GENERATED BY Argbash v2.10.0 one line above ###
@@ -27,7 +28,7 @@ die()
 
 begins_with_short_option()
 {
-	local first_option all_short_options='omahv'
+	local first_option all_short_options='amohv'
 	first_option="${1:0:1}"
 	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -36,19 +37,21 @@ begins_with_short_option()
 _positionals=()
 _arg_sources=(".")
 # THE DEFAULTS INITIALIZATION - OPTIONALS
-_arg_output=
-_arg_manifest="./manifest"
 _arg_archive=
+_arg_manifest="./manifest"
+_arg_output=
+_arg_verbose="off"
 
 
 print_help()
 {
 	printf '%s\n' "Generate archive and manifest"
-	printf 'Usage: %s [-o|--output <arg>] [-m|--manifest <arg>] [-a|--archive <arg>] [-h|--help] [-v|--version] [<sources-1>] ... [<sources-n>] ...\n' "$0"
+	printf 'Usage: %s [-a|--archive <arg>] [-m|--manifest <arg>] [-o|--output <arg>] [--(no-)verbose] [-h|--help] [-v|--version] [<sources-1>] ... [<sources-n>] ...\n' "$0"
 	printf '\t%s\n' "<sources>: sources to archive (defaults for <sources>: '.')"
-	printf '\t%s\n' "-o, --output: output file or - for stdout, (required) (no default)"
+	printf '\t%s\n' "-a, --archive: use existing archive (tar); filename or - for stdin (no default)"
 	printf '\t%s\n' "-m, --manifest: manifest file (default: './manifest')"
-	printf '\t%s\n' "-a, --archive: process existing archive (tar) (no default)"
+	printf '\t%s\n' "-o, --output: output file or - for stdout, (required) (no default)"
+	printf '\t%s\n' "--verbose, --no-verbose: write information to stderr (off by default)"
 	printf '\t%s\n' "-h, --help: Prints help"
 	printf '\t%s\n' "-v, --version: Prints version"
 }
@@ -61,16 +64,16 @@ parse_commandline()
 	do
 		_key="$1"
 		case "$_key" in
-			-o|--output)
+			-a|--archive)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_output="$2"
+				_arg_archive="$2"
 				shift
 				;;
-			--output=*)
-				_arg_output="${_key##--output=}"
+			--archive=*)
+				_arg_archive="${_key##--archive=}"
 				;;
-			-o*)
-				_arg_output="${_key##-o}"
+			-a*)
+				_arg_archive="${_key##-a}"
 				;;
 			-m|--manifest)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
@@ -83,16 +86,20 @@ parse_commandline()
 			-m*)
 				_arg_manifest="${_key##-m}"
 				;;
-			-a|--archive)
+			-o|--output)
 				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
-				_arg_archive="$2"
+				_arg_output="$2"
 				shift
 				;;
-			--archive=*)
-				_arg_archive="${_key##--archive=}"
+			--output=*)
+				_arg_output="${_key##--output=}"
 				;;
-			-a*)
-				_arg_archive="${_key##-a}"
+			-o*)
+				_arg_output="${_key##-o}"
+				;;
+			--no-verbose|--verbose)
+				_arg_verbose="on"
+				test "${1:0:5}" = "--no-" && _arg_verbose="off"
 				;;
 			-h|--help)
 				print_help
@@ -103,11 +110,11 @@ parse_commandline()
 				exit 0
 				;;
 			-v|--version)
-				echo $0 $archive_gen_version
+				echo $0 $archive_generate_version
 				exit 0
 				;;
 			-v*)
-				echo $0 $archive_gen_version
+				echo $0 $archive_generate_version
 				exit 0
 				;;
 			*)
@@ -186,24 +193,38 @@ abort() {
 	die "${0}: aborting"
 }
 
+verbose()
+{
+    if [ "${_arg_verbose}" = on ]
+    then
+	echo "$0" "$*" >&2
+    fi
+}
+
 trap abort HUP INT TERM ERR
 
-if [ ! ${_arg_output} ]
+# argument symantic error checking
+
+if [ -z ${_arg_output} ]
 then
     die "Error: \"-o|--output <filename\"> must be specified."
 fi
 
-if [ "${_arg_archive}" -a \( ! -f "${_arg_archive}" -o ! -r "${_arg_archive}" \) ]
+if [ -n "${_arg_archive}" ]
 then
-    die "Error: existing archive file \"${_arg_archive}\" not found or not a regualar, readable file"
+    if [ "${_positionals_count}" != 0 ]
+    then
+	die "Error: existing archive file or archive sources must be defined, but not both"
+    fi
+    if [ "${_arg_archive}" != '-' -a \( ! -f "${_arg_archive}" -o ! -r "${_arg_archive}" \) ]
+    then
+	die "Error: existing archive file \"${_arg_archive}\" not found or not a regular, readable file"
+    fi
 fi
 
-if [ "${_arg_archive}" -a "${_positionals_count}" != 0 ]
-then
-    die "Error: existing archive file or other sources must be defined, but not both"
-fi
+# build variables for command use and manifest
 
-archive_gen_command="$0 $@"
+archive_generate_command="$0 $@"
 archive_date_generated="$(date)"
 archive_uname="$(uname -a)"
 archive_cwd="$(pwd)"
@@ -219,21 +240,43 @@ archive_gpg="$(which gpg)"
 archive_gpg_version="$(gpg --version | head -1)"
 archive_tar="$(which tar)"
 
+# build command pipeline according to options
+
+cpipe=
+
 if [ "$_arg_archive" ]
 then
     archive_archive="$_arg_archive"
-                     cat < "$_arg_archive"               | gpg -c | tee >(shasum -a 256 > "$sha_file") >(wc -c >"$size_file") | cat > "$_arg_output"
-    archive_command="cat < "$_arg_archive"               | gpg -c | tee >(shasum -a 256 > "$sha_file") >(wc -c >"$size_file") | cat > "$_arg_output""
+    if [ "$archive_archive" != '-' ]
+    then
+	cpipe+='cat < "$archive_archive" | '		# else, consume stdin
+    fi
 else
     archive_sources=( "${_arg_sources[@]}" )
-                     tar -c -z -f - "${_arg_sources[@]}" | gpg -c | tee >(shasum -a 256 > "$sha_file") >(wc -c >"$size_file") | cat > "$_arg_output"
-    archive_command="tar -c -z -f - "${_arg_sources[@]}" | gpg -c | tee >(shasum -a 256 > "$sha_file") >(wc -c >"$size_file") | cat > "$_arg_output""
+    cpipe+='tar -c -z -f - "${archive_sources[@]}" | '
 fi
 
-archive_sha256=$(cat "$sha_file")
-archive_size=$(echo $(cat "$size_file"))
+cpipe+='gpg -c | tee >(shasum -a 256 > "$sha_file") >(wc -c >"$size_file")'
+
+if [ $archive_output != "-" ]
+then
+    cpipe+=' | cat > "$archive_output"'			# else, just send to stdout
+fi
+
+archive_command="$cpipe"
+
+verbose "running pipeline: '$cpipe'"
+
+eval $cpipe						# here we go!
+
+verbose "pipeline done"
+verbose "generating manifest"
 
 # print manifest
+
+first() {
+    echo $1
+}
 
 render_array() {
     	result="( "
@@ -244,6 +287,9 @@ render_array() {
 	result+=")"
 	echo "$result"
 }
+
+archive_sha256=$(first $(cat "$sha_file"))
+archive_size=$(first $(cat "$size_file"))
 
 (
 
@@ -275,15 +321,15 @@ cat <<- 'END'
 END
 
     printf '# Sources provided on command line: %s\n' "$_positionals_count"
-    for source in "${_arg_sources[@]}"
+    for source in "${archive_sources[@]}"
     do
 	printf '# Source: %s\n' "$source"
     done
 
     echo
 
-    printf 'archive_gen_command="%s"\n'		"$archive_gen_command"
-    printf 'archive_gen_version="%s"\n'		"$archive_gen_version"
+    printf 'archive_generate_command="%s"\n'	"$archive_generate_command"
+    printf 'archive_generate_version="%s"\n'	"$archive_generate_version"
     printf 'archive_date_generated="%s"\n'	"$archive_date_generated"
     printf 'archive_uname="%s"\n'		"$archive_uname"
     printf 'archive_cwd="%s"\n'			"$archive_cwd"
@@ -301,22 +347,26 @@ END
 
     printf '######### === BEGIN INFORMATION SECTION === #########\n'
 
-    if [ "$_arg_archive" ]
+    if [ "$archive_archive" ]
     then
 	printf '#### === BEGIN (tar) LS SECTION === ####\n'
-	tar tvf "$_arg_archive"
+	tar tvf "$archive_archive"
 	printf '#### === END (tar) LS SECTION === ####\n'
     else
 	printf '#### === BEGIN DU SECTION === ####\n'
-	du -s "${_arg_sources[@]}"
+	du -s "${archive_sources[@]}"
 	printf '#### === END DU SECTION === ####\n'
 	printf '#### === BEGIN LS SECTION === ####\n'
-	ls -l -R -A "${_arg_sources[@]}"
+	ls -l -R -A "${archive_sources[@]}"
 	printf '#### === END LS SECTION === ####\n'
     fi
 
     printf '######### === END INFORMATION SECTION === #########\n'
+
 ) > "$archive_manifest"
+
+verbose "manifest created: '$archive_manifest'"
+verbose "done, cleaning up"
 
 clean
 
